### PR TITLE
feat: add webrtc to supports

### PR DESCRIPTION
**Pull request by hugomrdias**

### CODE REVIEW

**Comment by hugomrdias** [comment]
Yhis can also be useful in ipfs and this repo already has the supports file, i would leave it here, but if you feel strongly about it we can definitely change it to libp2p.

**Comment by vasco-santos** [comment]
It feels strange to me to add an `ipfs` dependency into a `libp2p` module. Also for this context, `libp2p-webrtc-star` already uses `libp2p-utils` as its dependency

**Comment by hugomrdias** [comment]
ok, lets add it to libp2p-utils.
i will probably merge this here also, maybe be useful and its small.

**Comment by achingbrain** [comment]
Can we just have this sort of thing in a generic `i-can-has` module?  It's not really specific to ipfs or libp2p and would actually be useful outside of PL projects.

**Comment by vasco-santos** [comment]
> Can we just have this sort of thing in a generic i-can-has module? It's not really specific to ipfs or libp2p and would actually be useful outside of PL projects.

Yeah, ideally it would be to just use `webrtcsupport` module

**Comment by hugomrdias** [comment]
You guys know my opinion about creating new repos, but I'll support whatever.
Just keep in mind the changes I did to the feature test.

**Pull request merged**
